### ISSUE TITLE
Unable to find `schema.prisma` file

### ISSUE THREAD

**Issue by dawangraoming** [jetbridge/sst-prisma#45]
Hello, Teams. thank you for this project template, which has many brilliant designs and cool coding.

But some error here when using `sst` version **2.0**.

```text
|  Invoked backend/src/auth/trigger/preSignUp.handler

Error: ENOENT: no such file or directory, symlink '/Users/dawangraoming/Dcouments/sst-prisma/backend/prisma/schema.prisma' -> '/Users/dawangraoming/Dcouments/sst-prisma/.sst/artifacts/c8535e5c1e7834ed69d5556ed3b00d116bca4e4ef8/src/schema.prisma'

Trace: Error: ENOENT: no such file or directory, symlink '/Users/dawangraoming/Dcouments/sst-prisma/backend/prisma/schema.prisma' -> '/Users/dawangraoming/Dcouments/sst-prisma/.sst/artifacts/c8535e5c1e7834ed69d5556ed3b00d116bca4e4ef8/src/schema.prisma'
    at process.<anonymous> (file:///Users/dawangraoming/Dcouments/sst-prisma/node_modules/.pnpm/sst@2.0.23/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at processEmit [as emit] (/Users/dawangraoming/Dcouments/sst-prisma/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Need help with this error? Join the SST community on Discord https://sst.dev/discord
 ELIFECYCLE  Command failed with exit code 1.
```

--------

My procedure is

1. Set the environment variable `HOSTED_ZONE_NAME` to the `.env` file
2. Start via `pnpm dev`

And git hash is `fc0c92525c3d265539bb001075f548fd7512323e`

----------

Am I missing something?

**Comment by revmischa** [comment]
This should have been fixed in 54fee0b67f9c6a47b986e9590a00bfe8b2cc0395, sorry!

**Comment by revmischa** [comment]
Please let me know if any further issues. This should be resolved now

**Comment by chrisfitkin** [comment]
I'm experiencing this same error on a fresh clone after the #54fee0b commit.
